### ISSUE TITLE
Error with log-courier

### ISSUE THREAD

**Issue by ghost** [ucla-it-security/iso-elk-stack#2]
/opt/logstash/bin/logstash --configtest --config /etc/logstash/conf.d/logstash.conf
The error reported is:
  Couldn't find any input plugin named 'courier'. Are you sure this is correct? Trying to load the courier input plugin resulted in this error: no such file to load -- logstash/inputs/courier

**Comment by ghost** [comment]
I solved the problem by install  logstash-input-courier plugin
[root@logserver logstash]# pwd
/opt/logstash
[root@logserver logstash]# bin/plugin install logstash-input-courier
Validating logstash-input-courier
Installing logstash-input-courier
Installation successful
[root@logserver logstash]# /opt/logstash/bin/logstash --configtest --config /etc/logstash/conf.d/logstash.conf
Configuration OK

**Comment by ampodobas** [comment]
@tamqm: That's correct and noted in Step 5 of the "Install" tab of: https://www.itsecurity.ucla.edu/elk. I just put newly-written instructions up there today and I'll added a note on that to the README.
